-- =====================================================================
-- SYSPLAN WEB - SCHEMA COMPLETO (rodar uma vez no SQL Editor do Supabase)
-- Gerado em 2026-07-08 15:39
-- =====================================================================


-- ############ 00001_schema.sql ############

-- SysPlan Web — Schema principal
-- Convertido do Access (SysPlan_BD.accdb + tabelas locais do frontend)

-- =====================================================================
-- USUÁRIOS, PERFIS E PERMISSÕES
-- =====================================================================

create type perfil_usuario as enum ('admin', 'usuario');

create table usuarios (
  id uuid primary key references auth.users (id) on delete cascade,
  cd_usuario_legado integer unique,
  nome text not null default '',
  email text not null unique,
  login_rede text,
  filtro_comprador text default 'GERAL',
  perfil perfil_usuario not null default 'usuario',
  bloqueado boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Catálogo de telas/módulos do sistema (permissões por tela)
create table telas (
  codigo text primary key,
  nome text not null,
  grupo text not null default 'Sistema',
  ordem integer not null default 0
);

create table permissoes (
  usuario_id uuid not null references usuarios (id) on delete cascade,
  tela_codigo text not null references telas (codigo) on delete cascade,
  pode_visualizar boolean not null default true,
  pode_editar boolean not null default false,
  primary key (usuario_id, tela_codigo)
);

-- Log de auditoria (legado: DM_RegistroTransacao_Usuario)
create table log_transacoes (
  cd_transacao bigint generated by default as identity primary key,
  usuario_id uuid references usuarios (id),
  cd_usuario_legado integer,
  transacao text not null,
  cd_item_transacao integer default 0,
  dt_transacao timestamptz not null default now(),
  info_anterior text,
  info_atual text,
  campo_editado text
);

create index idx_log_transacoes_item on log_transacoes (cd_item_transacao);
create index idx_log_transacoes_dt on log_transacoes (dt_transacao desc);
create index idx_log_transacoes_usuario on log_transacoes (usuario_id);
create index idx_log_transacoes_transacao on log_transacoes (transacao);

-- =====================================================================
-- PARÂMETROS (PRM)
-- =====================================================================

create table prm_grupo (
  cd_grupo integer generated by default as identity primary key,
  dc_grupo text not null unique
);

create table prm_combos (
  cd_combo integer generated by default as identity primary key,
  cd_grupo integer not null references prm_grupo (cd_grupo),
  dc_tipo_combo text not null,
  dc_combo text not null
);
create index idx_prm_combos_tipo on prm_combos (cd_grupo, dc_tipo_combo);

create table prm_grupo_planejamento (
  dc_grupo text not null,
  dc_subgrupo text not null,
  dc_sexo text not null,
  dc_formato text not null,
  dc_grupo_planejamento text,
  primary key (dc_grupo, dc_subgrupo, dc_sexo, dc_formato)
);

create table prm_definicao_custo (
  dc_canal text not null,
  dc_grupo text not null,
  dc_modal text not null,
  nr_anomes numeric not null,
  nr_dolar double precision default 0,
  nr_fator_imp double precision default 0,
  nr_markup double precision default 0,
  nr_valor_agregado double precision default 0,
  primary key (dc_canal, dc_grupo, dc_modal, nr_anomes)
);

create table prm_cluster_comprador (
  cd_cluster integer generated by default as identity primary key,
  dc_grupo text,
  dc_canal text,
  dc_comprador text,
  dc_comprador_grupo text
);

create table prm_ajuste_fob (
  cd_pedido_sap text not null,
  cd_material_pai text not null,
  nr_fob double precision default 0,
  primary key (cd_pedido_sap, cd_material_pai)
);

create table prm_ajuste_pedido_sap_cadastro (
  id_sysplan integer primary key,
  cd_pedido_fornecedor text,
  cd_material_fornecedor text,
  cd_pedido_sap text,
  cd_material_pai text
);

create table prm_depara_pedido_multiplos_embarques (
  codigo integer generated by default as identity primary key,
  cd_pedido_sap text,
  cd_material_pai text,
  cd_embarque text,
  cd_pedido_sap_ajuste text
);
create index idx_prm_multiplos_chave on prm_depara_pedido_multiplos_embarques (cd_pedido_sap, cd_material_pai, cd_embarque);

create table prm_versao (
  versao_atual text primary key
);

-- Mapa de campos da edição em massa (legado: PRM_Campos_EdicaoMassa_Compras)
create table prm_campos_edicao_massa (
  dc_campo_edicao text primary key,
  dc_campo_original text,
  dc_campo_sysplan text
);

-- Dicionário de tradução de cores da PI (legado: PRM_Cor_PI)
create table prm_cor_pi (
  id integer generated always as identity primary key,
  dc_campo text,
  dc_texto_portugues text,
  dc_texto_ingles text,
  cd_codigo_cor text,
  ordem_pesquisa integer default 0
);

-- De-para de valores da PI para combos (legado: PRM_DePara_CamposPI)
create table prm_depara_campos_pi (
  id integer generated always as identity primary key,
  cd_grupo integer,
  dc_tipo_combo text,
  info_de text,
  info_para text
);

-- Configuração padrão de colunas da lista de compras (legado: PRM_Lista_Compras)
create table prm_lista_compras (
  campo text primary key,
  exibir text default 'SIM',
  tipo_filtro text default '',
  filtro text default '',
  largura_coluna integer default 100,
  legenda_exibicao text,
  ordem integer default 0,
  formatacao text,
  order_by text default 'NAO',
  tipo_dado text default 'Texto',
  largura_coluna_original integer default 100
);

-- Configuração de lista por usuário (novo: substitui config global do Access)
create table usuario_lista_config (
  usuario_id uuid not null references usuarios (id) on delete cascade,
  campo text not null references prm_lista_compras (campo) on delete cascade,
  exibir text default 'SIM',
  tipo_filtro text default '',
  filtro text default '',
  largura_coluna integer default 100,
  ordem integer default 0,
  order_by text default 'NAO',
  primary key (usuario_id, campo)
);

-- =====================================================================
-- CADASTROS DE APOIO
-- =====================================================================

create table cadastro_essential (
  cd_essential integer generated by default as identity primary key,
  dc_grupo text,
  dc_essential text,
  cd_material_pai_atual text,
  cd_ref_exportador_atual text,
  dc_status text,
  dc_reposicao_automatica text,
  vermelha boolean not null default false,
  otica boolean not null default false,
  dc_cluster_loja text,
  dc_status_vermelha text,
  dc_status_otica text
);

create table depara_essential (
  cd_material_pai text not null,
  cd_ref_exportador text not null,
  cd_essential text not null,
  primary key (cd_material_pai, cd_ref_exportador, cd_essential)
);

-- Snapshot do cadastro de materiais (legado: DB_Cadastro.accdb, linked)
create table cadastro_material (
  cd_material text primary key,
  cd_material_pai text,
  grupo2 text,
  dc_cor_lente_solar text,
  dc_cor_armacao text,
  dados jsonb
);
create index idx_cadastro_material_pai on cadastro_material (cd_material_pai);

create table cadastro_material_pai (
  cd_material_pai text primary key,
  dc_grupo text,
  grupo2 text,
  dados jsonb
);

-- =====================================================================
-- CONTROLE DE COMPRAS (tabela central)
-- =====================================================================

create table controle_compras (
  cd_compra integer generated by default as identity primary key,
  dc_status text,
  dc_canal text,
  dc_grupo text,
  dc_subgrupo text,
  dc_formato text,
  dc_sexo text,
  dc_segmentacao text,
  dc_grupo_planejamento text,
  dc_linha text,
  dc_griffe text,
  dc_material1 text,
  dc_material2 text,
  dc_atributo1 text,
  dc_atributo2 text,
  dc_medidas text,
  dc_tamanho text,
  dc_info1 text,
  dc_info2 text,
  dc_info3 text,
  dc_info4 text,
  dc_info5 text,
  dc_info6 text,
  dc_info7 text,
  nr_fob_negociado double precision default 0,
  nr_fob_real double precision default 0,
  nr_quantidade double precision default 0,
  nr_preco_varejo double precision default 0,
  nr_margem double precision default 0,
  cd_material_fornecedor text,
  cd_material_pai text,
  dc_fornecedor text,
  cd_pedido_fornecedor text,
  cd_pedido_sap text,
  dc_modal text,
  dt_recebimento date,
  dt_delivery date,
  dt_revised_delivery date,
  nr_lead_time double precision,
  dc_observacao text,
  nr_anomes numeric,
  bloqueio_edicao boolean not null default false,
  usuario_bloqueio uuid references usuarios (id),
  bloqueio_em timestamptz,
  dc_fup_produto text,
  cd_essential integer default 0,
  dc_aprovacao_cor text,
  nr_total_fob double precision default 0,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_compras_status on controle_compras (dc_status);
create index idx_compras_pedido_sap on controle_compras (cd_pedido_sap, cd_material_pai);
create index idx_compras_pedido_forn on controle_compras (cd_pedido_fornecedor, cd_material_fornecedor);
create index idx_compras_anomes on controle_compras (nr_anomes);
create index idx_compras_recebimento on controle_compras (dt_recebimento);
create index idx_compras_grupo_canal on controle_compras (dc_grupo, dc_canal);

-- =====================================================================
-- FOLLOW-UP DE FORNECEDOR
-- =====================================================================

create table followup_fornecedor (
  cd_follow_forn integer generated by default as identity primary key,
  -- sem FK estrita: dados legados possuem cd_compra=0/órfãos (Access não tinha FK)
  cd_compra integer not null default 0,
  dt_revised_delivery_original date,
  dt_recebimento_cb_original date,
  dc_modal_original text,
  dc_status_fornecedor text,
  dc_observacao_fornecedor text,
  dt_revised_delivery_proposta date,
  dc_numero_bl text,
  dc_avaliacao_fornecedor text,
  dc_avaliacao_comprador text,
  dc_observacao_avaliacao text,
  dt_novo_recebimento_comprador date,
  dt_novo_delivery_comprador date,
  dc_novo_modal_comprador text,
  dc_avaliacao_final text,
  dt_inicio_followup date,
  dt_fim_followup date,
  dt_avaliacao_comprador date
);

create index idx_followup_compra on followup_fornecedor (cd_compra);
create index idx_followup_fim on followup_fornecedor (dt_fim_followup);

-- =====================================================================
-- BASES EXTERNAS (snapshots atualizáveis por importação)
-- =====================================================================

create table ext_fup_comex (
  id bigint generated always as identity primary key,
  cd_sequencia_embarque text,
  cd_embarque text,
  cd_pedido_sap text,
  cd_material text,
  cd_material_pai text,
  dt_entrega_origem date,
  dt_previsao_embarque date,
  dt_embarque_real date,
  dt_previsao_atraque date,
  dt_atraque_real date,
  dt_chegada_cb date,
  nr_quantidade double precision,
  nr_fob_total double precision,
  dc_status_comex text
);
create index idx_fup_comex_chave on ext_fup_comex (cd_pedido_sap, cd_material_pai);
create index idx_fup_comex_embarque on ext_fup_comex (cd_embarque);

create table ext_fup_despachante (
  id bigint generated always as identity primary key,
  cd_pedido_sap text,
  cd_material_pai text,
  cd_embarque text,
  dt_entrega_origem date,
  dt_previsao_embarque date,
  dt_embarque_real date,
  dt_previsao_atraque date,
  dt_atraque_real date,
  hbl text,
  dc_status_comex text,
  dc_observacao text,
  origem text
);
create index idx_fup_desp_chave on ext_fup_despachante (cd_pedido_sap, cd_material_pai);

create table ext_pedido_sap (
  id bigint generated always as identity primary key,
  cd_pedido_sap text,
  cd_material text,
  cd_material_pai text,
  nr_valor_fob numeric,
  nr_quantidade numeric,
  dc_modal text,
  dc_cor_lente_solar text,
  dc_cor_armacao text
);
create index idx_pedido_sap_chave on ext_pedido_sap (cd_pedido_sap, cd_material_pai);

-- Snapshot do extrator SAP BW (legado: dbo./BIC/OHZSETTB023)
create table ext_sap_pedido_bw (
  comp_code text not null,
  oi_ebeln text not null,
  oi_ebelp text not null,
  recordmode text,
  material text,
  txt_material text,
  erdat text,
  vendor text,
  ca_impna text,
  dsdel_date text,
  doctype text,
  net_po_val numeric,
  ttlqty numeric,
  base_uom text,
  ca_modal text,
  txtlg text,
  order_curr text,
  primary key (comp_code, oi_ebeln, oi_ebelp)
);
create index idx_sap_bw_material on ext_sap_pedido_bw (material);

-- Entradas SAP MB51 (staging de conferência de recebimento)
create table stg_entrada_sap_mb51 (
  id bigint generated always as identity primary key,
  material text,
  centro text,
  deposito text,
  tipo_movimento text,
  txt_tipo_movimento text,
  doc_material text,
  item_doc_material text,
  dt_lancamento date,
  qtd_um_registro double precision,
  um_registro text,
  montante_mi double precision,
  referencia text,
  cliente text,
  fornecedor text,
  nome1 text,
  nome_usuario text,
  pedido text,
  texto_breve_material text,
  importado_em timestamptz not null default now()
);
create index idx_mb51_chave on stg_entrada_sap_mb51 (pedido, material);

-- =====================================================================
-- CADASTRO DE PI (Proforma Invoice)
-- =====================================================================

create table pasta_pi (
  dc_nome_arquivo text primary key,
  dc_caminho_arquivo text,
  dc_tipo_arquivo text,
  dt_modificacao_arquivo timestamptz,
  dc_status_movimentacao text,
  cd_sysplan integer default 0,
  dc_sore text,
  cd_pi text,
  dt_delivery_date date,
  cd_ref_fornecedor text,
  dc_fornecedor text,
  dc_reorder text,
  cd_last_model text,
  dc_griffe text,
  nr_qtd_total double precision default 0,
  nr_fob_total double precision default 0,
  dc_frame1 text,
  dc_frame2 text,
  dc_lens text,
  dc_atributo1 text,
  dc_atributo2 text,
  dc_atributo3 text,
  dc_flap text,
  dc_hinge text,
  dc_size text,
  dc_temple1 text,
  dc_temple2 text,
  dc_bridge text,
  dc_rim text,
  dc_tips text,
  dc_nose_pad text,
  dc_lens_category text,
  dc_lens_tratamento1 text,
  dc_lens_tratamento2 text,
  dc_clipon_type text,
  dc_possui_foto text,
  storage_path_arquivo text,
  storage_path_foto text,
  importado_por uuid references usuarios (id),
  importado_em timestamptz default now()
);

-- Cores extraídas da PI (por importação; legado: AUX_Import_PI_Cores)
create table pi_cores (
  id bigint generated always as identity primary key,
  dc_nome_arquivo text not null references pasta_pi (dc_nome_arquivo) on delete cascade,
  dc_numero_cor text,
  dc_cor_lente text,
  dc_cor_armacao text,
  dc_acabamento_armacao text,
  dc_cor_haste text,
  dc_acabamento_haste text,
  nr_qtde double precision default 0,
  nr_fob double precision default 0,
  dc_idioma text not null default 'PORTUGUES',
  nr_total_fob double precision
);

-- =====================================================================
-- MÓDULO DESIGN (estrutura preservada do legado, sem dados)
-- =====================================================================

create table desenvolvimento_design (
  cd_desenvolv integer generated by default as identity primary key,
  cd_compra integer default 0,
  dc_fornecedor text,
  cd_codigo1 text,
  cd_codigo2 text,
  dt_escolha_modelagem date,
  dt_desenv_aprov_caito date,
  dt_desenvolv_envio_fornecedor date,
  dt_desenvolv_envio_licenciamento date,
  dt_desenho_tecnico_aprovacao date,
  dt_prototipo_aprovacao date,
  dt_prototipo_aprovacao_caito date,
  dt_lente_acetato_aprovacao date,
  dc_desenvolv_obs text,
  dc_desenvolv_status text
);

create table cartela_cor_design (
  cd_cor_design integer generated by default as identity primary key,
  cd_desenvolv integer references desenvolvimento_design (cd_desenvolv) on delete cascade,
  dc_cor_status text,
  dt_cor_aprovacao date,
  dt_cor_aprovacao_licenciamento date,
  dt_cor_aprovacao_caito date,
  dt_rec_foto_amostra date,
  dt_rec_amostra_fisica date,
  dt_rec_foto_amostra_final date,
  dt_rec_amostra_fisica_final date,
  dt_foto_final_envio_licenciamento date
);

-- =====================================================================
-- MÓDULO PDV (snapshot das tabelas CIG do SQL Server)
-- =====================================================================

create table pdv_cadastro_loja (
  cd_sap text primary key,
  dc_loja text,
  dc_canal text,
  dc_grupo_loja text,
  dc_franqueado text,
  dc_uf text,
  dc_estado text,
  dc_cidade text,
  dc_bairro text,
  dados jsonb
);

create table pdv_cadastro_pdv (
  id_pdv integer generated by default as identity primary key,
  cd_pdv text,
  dc_pdv text,
  dc_canal text,
  dc_tipo_pdv text,
  dc_franqueado text,
  dc_uf text,
  dc_estado text,
  dc_cidade text,
  dc_bairro text,
  dados jsonb
);

create table pdv_base_cadastro (
  cd_sap text primary key,
  dt_inicio_var date,
  dt_fim_var date,
  dt_inicio_atac date,
  dt_fim_atac date,
  dt_inicio_dev date,
  dt_fim_dev date,
  ultimo_movimento date,
  dados jsonb
);

create table pdv_depara (
  id_pdv integer not null,
  cd_sap text not null primary key
);

create table pdv_status (
  id bigint generated always as identity primary key,
  dados jsonb
);

-- =====================================================================
-- IMPORTAÇÕES / EXPORTAÇÕES (controle de jobs)
-- =====================================================================

create table importacoes (
  id bigint generated always as identity primary key,
  usuario_id uuid references usuarios (id),
  tipo text not null,           -- edicao_massa | followup_fornecedor | fup_despachante | mb51 | pi | pedido_sap_bw | ...
  nome_arquivo text,
  total_linhas integer default 0,
  linhas_validas integer default 0,
  linhas_erro integer default 0,
  status text not null default 'validando',  -- validando | aguardando_confirmacao | aplicado | cancelado | erro
  inconsistencias jsonb,
  criado_em timestamptz not null default now(),
  aplicado_em timestamptz
);

-- ############ 00002_funcoes_views.sql ############

-- SysPlan Web — Funções e views (regras de negócio convertidas do VBA/consultas Access)

-- =====================================================================
-- FUNÇÕES DE NEGÓCIO
-- =====================================================================

-- Define_TamanhoProduto (VBA Módulo1)
create or replace function fn_tamanho_produto(p_grupo text, p_medidas text, p_sexo text)
returns text language plpgsql immutable as $$
declare
  v_partes text[];
  v_lente numeric := 0;
  v_ponte numeric := 0;
  v_lente_ponte numeric := 0;
  v_medida numeric := 0;
begin
  if p_grupo in ('OCULOS', 'MULTI', 'VISTA') then
    v_partes := string_to_array(replace(replace(coalesce(p_medidas, ''), '#', '-'), ' ', '-'), '-');
    begin
      v_lente := coalesce(nullif(trim(v_partes[1]), ''), '0')::numeric;
      v_ponte := coalesce(nullif(trim(v_partes[2]), ''), '0')::numeric;
    exception when others then
      v_lente := 0; v_ponte := 0;
    end;
    if v_lente < 1 or v_ponte < 1 or v_ponte > 40 then
      v_lente_ponte := 0;
    else
      v_lente_ponte := v_lente + v_ponte;
    end if;
    if v_lente_ponte > 0 then
      return case
        when v_lente_ponte <= 68 then 'P'
        when v_lente_ponte <= 73 then 'M'
        when v_lente_ponte <= 76 then 'G'
        else 'GG'
      end;
    end if;
    return 'N/I';
  elsif p_grupo in ('RELOGIO', 'SMART WATCH', 'RELOGIOS') then
    begin
      v_medida := coalesce(nullif(trim(p_medidas), ''), '0')::numeric;
    exception when others then
      v_medida := 0;
    end;
    if p_sexo in ('MASCULINO', 'UNISSEX') then
      return case
        when v_medida <= 1 then 'N/I'
        when v_medida <= 36 then 'PPP'
        when v_medida <= 40 then 'PP'
        when v_medida <= 43 then 'P'
        when v_medida <= 47 then 'M'
        when v_medida <= 51 then 'G'
        else 'GG'
      end;
    elsif p_sexo = 'FEMININO' then
      return case
        when v_medida <= 1 then 'N/I'
        when v_medida <= 28 then 'PPP'
        when v_medida <= 32 then 'PP'
        when v_medida <= 36 then 'P'
        when v_medida <= 40 then 'M'
        when v_medida <= 43 then 'G'
        else 'GG'
      end;
    end if;
    return 'N/I';
  end if;
  return null;
end;
$$;

-- CalcMargem (VBA Módulo1): margem = 1 - custo/atacado
create or replace function fn_calc_margem(
  p_canal text, p_grupo text, p_modal text,
  p_fob double precision, p_pv_varejo double precision, p_dt_rec date
) returns double precision language sql stable as $$
  select case
    when c.nr_markup is null or c.nr_markup = 0 then null
    when (p_pv_varejo / c.nr_markup - c.nr_valor_agregado) = 0 then null
    else 1 - (p_fob * c.nr_fator_imp * c.nr_dolar)
             / (p_pv_varejo / c.nr_markup - c.nr_valor_agregado)
  end
  from prm_definicao_custo c
  where c.dc_canal = p_canal and c.dc_grupo = p_grupo and c.dc_modal = p_modal
    and c.nr_anomes = to_char(coalesce(p_dt_rec, '1899-12-30'::date), 'YYYYMM')::numeric
  limit 1;
$$;

-- PriorizaInfo_Comex (VBA): 3=Comex, 2=Despachante, 1=Fornecedor, 0=sem info
create or replace function fn_prioriza_info_comex(
  p_status_produto text, p_status_despachante text, p_status_comex text
) returns integer language sql immutable as $$
  select case
    when coalesce(p_status_comex, '') <> '' and coalesce(p_status_comex, '') <> 'AE - AG ENTREGA NA ORIGEM' then
      case
        when coalesce(p_status_comex, '') = 'LE - AG EMBARQUE' and coalesce(p_status_despachante, '') = 'Embarcado' then 2
        else 3
      end
    when coalesce(p_status_despachante, '') <> ''
      and coalesce(p_status_despachante, '') not in ('Pendente entrega na origem - ATRASADO', 'Pendente entrega na origem - NO PRAZO', 'ID Origem não informado') then 2
    when coalesce(p_status_produto, '') <> '' then 1
    else 0
  end;
$$;

-- GrupoStatus_Comex (VBA): classificação para o painel de importação
create or replace function fn_grupo_status_comex(
  p_status text, p_delivery date, p_info_usar integer, p_processo text, p_base_despachante text
) returns text language sql stable as $$
  select case
    when p_info_usar = 1 then
      case
        when p_delivery is not null and p_delivery > current_date - 7 then 'PRODUTO - Delivery futuro'
        when p_status = 'DELIVERED' then
          case
            when p_base_despachante = 'Nao' then 'PRODUTO - Fora base despachante'
            when coalesce(p_processo, '') <> '' then 'COMEX - Confirmar entrega na origem'
            else 'PRODUTO - Delivery sem numero BL'
          end
        when p_status = 'WAITING - BOARDING INSTRUCTION' then 'COMEX - Pendente SO'
        else 'PRODUTO - Pendencia Follow up'
      end
    else p_status
  end;
$$;

-- Validacao_ListaEntrega (VBA)
create or replace function fn_validacao_lista_entrega(
  p_lead_time double precision, p_material_pai text, p_pedido_sap text, p_status text, p_modal text
) returns text language plpgsql immutable as $$
declare
  v_modal text := left(coalesce(p_modal, ''), 3);
  v_ini integer; v_fim integer;
  v_erros text := '';
begin
  v_ini := case when v_modal = 'AIR' then 15 else 60 end;
  v_fim := case when v_modal = 'AIR' then 59 else 100 end;
  if coalesce(p_lead_time, 0) < v_ini or coalesce(p_lead_time, 0) > v_fim then
    v_erros := 'Modal Fora do espetado';
  end if;
  if coalesce(p_status, '') = 'Aberto' or coalesce(p_status, '') = 'ABERTO' then
    v_erros := v_erros || case when v_erros <> '' then ' | ' else '' end || 'Pedido em Aberto';
  end if;
  if length(coalesce(p_material_pai, '')) <> 8 then
    v_erros := v_erros || case when v_erros <> '' then ' | ' else '' end || 'Erro Material Pai';
  end if;
  if length(coalesce(p_pedido_sap, '')) <> 10 then
    v_erros := v_erros || case when v_erros <> '' then ' | ' else '' end || 'Erro Pedido SAP';
  end if;
  if v_erros = '' then
    return 'OK';
  end if;
  return 'Erro: ' || v_erros;
end;
$$;

-- AvaliacaoFollow_fornecedor (VBA)
create or replace function fn_avaliacao_followup(
  p_status_forn text, p_delivery_atual date, p_delivery_proposta date
) returns text language sql immutable as $$
  select case
    when coalesce(p_status_forn, '') ilike '%WAIT%' then 'PENDENTE'
    when p_delivery_proposta is distinct from p_delivery_atual then 'PENDENTE'
    else 'OK'
  end;
$$;

-- Helpers de autorização
create or replace function fn_usuario_atual() returns uuid
language sql stable security definer set search_path = public as $$
  select id from usuarios where id = auth.uid() and not bloqueado;
$$;

create or replace function fn_is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from usuarios where id = auth.uid() and perfil = 'admin' and not bloqueado
  );
$$;

create or replace function fn_tem_permissao(p_tela text, p_editar boolean default false)
returns boolean language sql stable security definer set search_path = public as $$
  select fn_is_admin() or exists (
    select 1 from permissoes p
    join usuarios u on u.id = p.usuario_id
    where p.usuario_id = auth.uid()
      and p.tela_codigo = p_tela
      and not u.bloqueado
      and p.pode_visualizar
      and (not p_editar or p.pode_editar)
  );
$$;

-- Registro de log (equivalente a RegistraTransacao do VBA)
create or replace function fn_registra_transacao(
  p_transacao text, p_item integer default 0,
  p_info_anterior text default '', p_info_atual text default '', p_campo text default ''
) returns void language sql security definer set search_path = public as $$
  insert into log_transacoes (usuario_id, transacao, cd_item_transacao, info_anterior, info_atual, campo_editado)
  values (auth.uid(), p_transacao, coalesce(p_item, 0), p_info_anterior, p_info_atual, p_campo);
$$;

-- =====================================================================
-- TRIGGERS
-- =====================================================================

-- Auditoria campo a campo em controle_compras (equivalente a Registra_Info/PRM_Campos_EdicaoMassa)
create or replace function trg_audita_controle_compras() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_col text;
  v_old text;
  v_new text;
begin
  if tg_op = 'INSERT' then
    insert into log_transacoes (usuario_id, transacao, cd_item_transacao)
    values (auth.uid(), 'EdicaoCompra - Criacao', new.cd_compra);
    return new;
  end if;
  for v_col in
    select column_name from information_schema.columns
    where table_schema = 'public' and table_name = 'controle_compras'
      and column_name not in ('atualizado_em', 'criado_em', 'bloqueio_edicao', 'usuario_bloqueio', 'bloqueio_em', 'nr_margem', 'nr_anomes', 'nr_lead_time')
  loop
    execute format('select ($1).%I::text, ($2).%I::text', v_col, v_col) into v_old, v_new using old, new;
    if v_old is distinct from v_new then
      insert into log_transacoes (usuario_id, transacao, cd_item_transacao, info_anterior, info_atual, campo_editado)
      values (auth.uid(), 'EdicaoCompra - Alteracao', new.cd_compra, coalesce(v_old, ''), coalesce(v_new, ''), v_col);
    end if;
  end loop;
  return new;
end;
$$;

create trigger audita_controle_compras
  after insert or update on controle_compras
  for each row execute function trg_audita_controle_compras();

-- Campos calculados mantidos pelo banco (lead time, ano-mês, tamanho, exclusão lógica)
create or replace function trg_calcula_controle_compras() returns trigger
language plpgsql as $$
begin
  new.nr_lead_time := case
    when new.dt_recebimento is not null and new.dt_revised_delivery is not null
    then new.dt_recebimento - new.dt_revised_delivery
    else new.nr_lead_time
  end;
  new.nr_anomes := case
    when new.dt_recebimento is not null then to_char(new.dt_recebimento, 'YYYYMM')::numeric
    else new.nr_anomes
  end;
  new.dc_tamanho := coalesce(fn_tamanho_produto(new.dc_grupo, new.dc_medidas, new.dc_sexo), new.dc_tamanho);
  new.atualizado_em := now();
  return new;
end;
$$;

create trigger calcula_controle_compras
  before insert or update on controle_compras
  for each row execute function trg_calcula_controle_compras();

-- Perfil criado automaticamente ao registrar usuário no Auth
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.usuarios (id, email, nome, perfil)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'nome', split_part(new.email, '@', 1)),
    case when (new.raw_user_meta_data ->> 'perfil') = 'admin' then 'admin'::perfil_usuario else 'usuario'::perfil_usuario end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =====================================================================
-- VIEWS (consultas do Access)
-- =====================================================================

-- Qry_FOB_SAP
create or replace view vw_fob_sap as
select cd_material_pai, cd_pedido_sap,
       sum(nr_valor_fob) / nullif(sum(nr_quantidade), 0) as fob_sap
from ext_pedido_sap
group by cd_material_pai, cd_pedido_sap;

-- Qry_Resumo_FUP_Comex (com ajuste de múltiplos embarques)
create or replace view vw_resumo_fup_comex as
select
  max(f.cd_embarque) as cd_embarque,
  coalesce(m.cd_pedido_sap_ajuste, f.cd_pedido_sap) as cd_pedido_sap,
  f.cd_material_pai,
  max(f.dt_entrega_origem) as dt_entrega_origem,
  max(f.dt_previsao_embarque) as dt_previsao_embarque,
  max(f.dt_embarque_real) as dt_embarque_real,
  max(f.dt_previsao_atraque) as dt_previsao_atraque,
  max(f.dt_atraque_real) as dt_atraque_real,
  max(f.dt_chegada_cb) as dt_chegada_cb,
  sum(f.nr_quantidade) as nr_quantidade,
  sum(f.nr_fob_total) as nr_fob_total,
  max(f.dc_status_comex) as dc_status_comex
from ext_fup_comex f
left join prm_depara_pedido_multiplos_embarques m
  on f.cd_embarque = m.cd_embarque
 and f.cd_material_pai = m.cd_material_pai
 and f.cd_pedido_sap = m.cd_pedido_sap
group by coalesce(m.cd_pedido_sap_ajuste, f.cd_pedido_sap), f.cd_material_pai
having max(f.dc_status_comex) <> 'AE - AG ENTREGA NA ORIGEM';

-- Qry_Resumo_FUP_Despachante
create or replace view vw_resumo_fup_despachante as
select
  cd_pedido_sap,
  cd_material_pai,
  max(cd_embarque) as cd_embarque,
  max(dt_entrega_origem) as dt_entrega_origem,
  max(dt_previsao_embarque) as dt_previsao_embarque,
  max(dt_embarque_real) as dt_embarque_real,
  max(dt_previsao_atraque) as dt_previsao_atraque,
  max(dt_atraque_real) as dt_atraque_real,
  max(hbl) as hbl,
  max(dc_status_comex) as dc_status_comex,
  max(dc_observacao) as dc_observacao,
  max(origem) as origem
from ext_fup_despachante
group by cd_pedido_sap, cd_material_pai;

-- Qry_FiltroFollow_Forn_UltimaResp + ComResp: último follow respondido por compra
create or replace view vw_followup_ultima_resposta as
select f.cd_compra, max(f.cd_follow_forn) as cd_follow
from followup_fornecedor f
join (
  select cd_compra, max(dt_fim_followup) as max_fim
  from followup_fornecedor
  where dt_fim_followup is not null
  group by cd_compra
) u on u.cd_compra = f.cd_compra and u.max_fim = f.dt_fim_followup
where f.dt_fim_followup is not null
group by f.cd_compra;

-- Qry_FiltroFollow_Forn_SemResp: follows abertos
create or replace view vw_followup_sem_resposta as
select cd_compra, max(cd_follow_forn) as cd_follow
from followup_fornecedor
where dt_fim_followup is null
group by cd_compra;

-- Qry_Resumo_FUP_Geral: consolidação Comex > Despachante > Fornecedor por compra
create or replace view vw_resumo_fup_geral as
select
  c.cd_compra,
  fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex) as info_usar,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.cd_embarque
    when 2 then coalesce(x.cd_embarque, d.cd_embarque)
    when 1 then ff.dc_numero_bl
    else ''
  end as processo_calc,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.dc_status_comex
    when 2 then d.dc_status_comex || ' - Fora FUP'
    when 1 then ff.dc_status_fornecedor
    else 'SEM FOLLOW UP'
  end as status_calc,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.dt_entrega_origem
    when 2 then d.dt_entrega_origem
    else c.dt_revised_delivery
  end as entrega_calc,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.dt_previsao_embarque when 2 then d.dt_previsao_embarque else null
  end as prev_embarque_calc,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.dt_embarque_real when 2 then d.dt_embarque_real else null
  end as embarque_calc,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.dt_previsao_atraque when 2 then d.dt_previsao_atraque else null
  end as prev_atraque_calc,
  case fn_prioriza_info_comex(ff.dc_status_fornecedor, d.dc_status_comex, x.dc_status_comex)
    when 3 then x.dt_atraque_real when 2 then d.dt_atraque_real else null
  end as atraque_calc,
  case when d.cd_pedido_sap is null then 'Nao' else 'Sim' end as consta_despachante
from controle_compras c
left join vw_resumo_fup_comex x
  on c.cd_pedido_sap = x.cd_pedido_sap and c.cd_material_pai = x.cd_material_pai
left join vw_resumo_fup_despachante d
  on c.cd_pedido_sap = d.cd_pedido_sap and c.cd_material_pai = d.cd_material_pai
left join vw_followup_ultima_resposta ur on c.cd_compra = ur.cd_compra
left join followup_fornecedor ff on ur.cd_follow = ff.cd_follow_forn
where c.dc_status is distinct from 'EXCLUIDO';

-- Qry_ControleCompras_Lista: fonte da tela principal
create or replace view vw_controle_compras_lista as
select
  c.*,
  case when fob.fob_sap > 0 then fob.fob_sap else c.nr_fob_negociado end as fob_calc,
  case
    when cu.nr_markup is null or cu.nr_markup = 0 then null
    when (c.nr_preco_varejo / cu.nr_markup - cu.nr_valor_agregado) = 0 then null
    else 1 - ((case when fob.fob_sap > 0 then fob.fob_sap else c.nr_fob_negociado end) * cu.nr_fator_imp * cu.nr_dolar)
           / (c.nr_preco_varejo / cu.nr_markup - cu.nr_valor_agregado)
  end as margem_calc,
  fn_tamanho_produto(c.dc_grupo, c.dc_medidas, c.dc_sexo) as tamanho_calc,
  g.processo_calc as cd_embarque,
  g.entrega_calc as dt_entrega_origem_fup,
  coalesce(g.embarque_calc, g.prev_embarque_calc) as dt_embarque_fup,
  coalesce(g.atraque_calc, g.prev_atraque_calc) as dt_atraque_fup,
  g.status_calc as dc_status_comex,
  case when coalesce(c.cd_essential, 0) <> 0
       then c.cd_essential::text || ' - ' || coalesce(e.dc_essential, '')
       else '' end as essential_calc,
  cc.dc_comprador,
  cc.dc_comprador_grupo as dc_comprador_grupo
from controle_compras c
left join prm_definicao_custo cu
  on c.dc_grupo = cu.dc_grupo and c.dc_canal = cu.dc_canal
 and c.dc_modal = cu.dc_modal and c.nr_anomes = cu.nr_anomes
left join vw_fob_sap fob
  on c.cd_pedido_sap = fob.cd_pedido_sap and c.cd_material_pai = fob.cd_material_pai
left join prm_cluster_comprador cc
  on c.dc_grupo = cc.dc_grupo and c.dc_canal = cc.dc_canal
left join vw_resumo_fup_geral g on c.cd_compra = g.cd_compra
left join cadastro_essential e on c.cd_essential = e.cd_essential
where c.dc_status is distinct from 'EXCLUIDO';

-- Qry_Analise_FUP_Comex: painel de controle de importação
create or replace view vw_analise_fup_comex as
select
  c.cd_compra, c.dc_canal, c.dc_grupo, c.dc_linha, c.dc_griffe,
  c.cd_material_pai, c.cd_pedido_sap, c.nr_quantidade,
  c.dt_recebimento, c.dt_revised_delivery, c.dc_modal,
  g.processo_calc, g.status_calc, g.info_usar,
  g.entrega_calc, g.prev_embarque_calc, g.embarque_calc,
  g.prev_atraque_calc, g.atraque_calc,
  fn_grupo_status_comex(g.status_calc, c.dt_revised_delivery, g.info_usar, g.processo_calc, g.consta_despachante) as grupo_status,
  to_char(c.dt_recebimento, 'YYYYMM')::numeric as nr_anomes
from controle_compras c
join vw_resumo_fup_geral g on c.cd_compra = g.cd_compra
where c.dc_modal is distinct from 'ROAD'
  and to_char(c.dt_recebimento, 'YYYYMM') >= to_char(current_date - 1, 'YYYYMM');

-- Qry_FupComex_ListaEntregaOrigem
create or replace view vw_lista_entrega_origem as
select
  case when c.dc_grupo = 'MATERIAIS CONSUMIVEIS' then c.dc_subgrupo else c.dc_grupo end as grupo,
  c.dc_linha, c.dc_griffe, c.dc_canal, c.dc_fornecedor,
  c.cd_material_pai, c.cd_pedido_fornecedor, c.cd_pedido_sap,
  c.nr_quantidade, c.dt_recebimento, c.dc_modal, c.dt_revised_delivery,
  (c.dt_recebimento - c.dt_revised_delivery) as lead_time,
  fn_validacao_lista_entrega((c.dt_recebimento - c.dt_revised_delivery)::double precision,
    c.cd_material_pai, c.cd_pedido_sap, c.dc_status, c.dc_modal) as avaliacao,
  to_char(c.dt_revised_delivery, 'YYYYMM') as anomes_delivery
from vw_resumo_fup_geral g
join controle_compras c on g.cd_compra = c.cd_compra
where c.dc_modal is distinct from 'ROAD'
  and to_char(c.dt_recebimento, 'YYYYMM') >= to_char(current_date - 1, 'YYYYMM')
  and c.dc_status is distinct from 'EXCLUIDO';

-- Qry_FollowFornecedor_Pendente
create or replace view vw_followup_pendente as
select
  f.cd_follow_forn, f.cd_compra, c.dc_fornecedor, c.cd_pedido_fornecedor,
  c.cd_material_fornecedor, c.cd_pedido_sap, c.cd_material_pai,
  c.dc_grupo || ' ' || coalesce(c.dc_canal, '') as grupo,
  coalesce(c.dc_linha, '') || ' | ' || coalesce(c.dc_griffe, '') as colecao,
  f.dt_revised_delivery_original as delivery_date_atual,
  f.dt_recebimento_cb_original as dt_recebimento_atual,
  f.dc_modal_original as dc_modal_atual,
  cc.dc_comprador, cc.dc_comprador_grupo
from followup_fornecedor f
join controle_compras c on f.cd_compra = c.cd_compra
left join vw_resumo_fup_comex x
  on c.cd_pedido_sap = x.cd_pedido_sap and c.cd_material_pai = x.cd_material_pai
left join prm_cluster_comprador cc
  on c.dc_canal = cc.dc_canal and c.dc_grupo = cc.dc_grupo
where f.dt_recebimento_cb_original >= date_trunc('month', current_date)
  and f.dt_fim_followup is null
  and x.dt_entrega_origem is null
  and c.dc_status is distinct from 'EXCLUIDO';

-- Qry_Resumo_EntradaSAP_MB51
create or replace view vw_resumo_entrada_mb51 as
select
  s.deposito as cd_deposito,
  left(s.material, 8) as material_pai,
  s.pedido,
  max(s.dt_lancamento) as dt_recebimento,
  sum(s.qtd_um_registro) as qtde
from stg_entrada_sap_mb51 s
left join cadastro_material m on s.material = m.cd_material
where s.deposito in ('3003', '3008', '3001')
  and (m.grupo2 is null or m.grupo2 in ('OCULOS', 'RELOGIOS', 'MULTI', 'VISTA', 'MATERIAIS CONSUMIVEIS', 'KIDS'))
group by s.deposito, left(s.material, 8), s.pedido;

-- Múltiplos embarques: pedidos com mais de um embarque
create or replace view vw_fup_multiplos_embarques as
select cd_pedido_sap, cd_material_pai, count(distinct cd_embarque) as qtde_embarques
from ext_fup_comex
group by cd_pedido_sap, cd_material_pai
having count(distinct cd_embarque) > 1;

-- Qry_MultiplosEmbarques_PendenteAbertura_ControleCompras
create or replace view vw_multiplos_embarques_pendentes as
select
  m.cd_pedido_sap, m.cd_material_pai, m.cd_pedido_sap_ajuste, m.cd_embarque,
  f.dc_status_comex,
  max(f.dt_chegada_cb) as rec_fup,
  sum(f.nr_quantidade) as qtde_fup,
  cc.dc_comprador, cc.dc_comprador_grupo,
  c.dt_recebimento as rec_compra
from prm_depara_pedido_multiplos_embarques m
join ext_fup_comex f
  on m.cd_embarque = f.cd_embarque
 and m.cd_material_pai = f.cd_material_pai
 and m.cd_pedido_sap = f.cd_pedido_sap
left join controle_compras c
  on m.cd_pedido_sap_ajuste = c.cd_pedido_sap and m.cd_material_pai = c.cd_material_pai
 and c.dc_status is distinct from 'EXCLUIDO'
left join prm_cluster_comprador cc
  on c.dc_canal = cc.dc_canal and c.dc_grupo = cc.dc_grupo
where coalesce(m.cd_pedido_sap_ajuste, '') <> ''
group by m.cd_pedido_sap, m.cd_material_pai, m.cd_pedido_sap_ajuste, m.cd_embarque,
         f.dc_status_comex, cc.dc_comprador, cc.dc_comprador_grupo, c.dt_recebimento
having c.dt_recebimento >= '2024-01-01' or c.dt_recebimento is null;

-- Checks de recebimento (auditoria)
create or replace view vw_check_pi_duplicado as
select dc_grupo as grupo, cd_pedido_fornecedor as pi, cd_material_fornecedor as material,
       max(dt_recebimento) as rec, count(cd_compra) as qtd_linhas,
       max(dc_canal) as canal1, min(dc_canal) as canal2
from controle_compras
where dc_status is distinct from 'EXCLUIDO'
group by dc_grupo, cd_pedido_fornecedor, cd_material_fornecedor
having dc_grupo <> 'MATERIAIS CONSUMIVEIS'
   and coalesce(cd_pedido_fornecedor, '') not in ('', 'N/I')
   and max(dt_recebimento) >= '2025-01-01'
   and count(cd_compra) > 1;

create or replace view vw_check_po_duplicado as
select dc_grupo as grupo, cd_pedido_sap as po, cd_material_pai as material,
       max(dt_recebimento) as rec, count(cd_compra) as qtd_linhas,
       max(dc_canal) as canal1, min(dc_canal) as canal2
from controle_compras
where dc_status is distinct from 'EXCLUIDO'
group by dc_grupo, cd_pedido_sap, cd_material_pai
having dc_grupo <> 'MATERIAIS CONSUMIVEIS'
   and coalesce(cd_pedido_sap, '') > '0' and cd_pedido_sap <> 'N/I'
   and max(dt_recebimento) >= '2025-01-01'
   and count(cd_compra) > 1;

create or replace view vw_check_gp_nao_cadastrado as
select c.dc_grupo, c.dc_subgrupo, c.dc_formato, c.dc_sexo
from controle_compras c
left join prm_grupo_planejamento g
  on c.dc_grupo = g.dc_grupo and c.dc_subgrupo = g.dc_subgrupo
 and c.dc_sexo = g.dc_sexo and c.dc_formato = g.dc_formato
where g.dc_grupo is null
group by c.dc_grupo, c.dc_subgrupo, c.dc_formato, c.dc_sexo;

-- =====================================================================
-- PROCEDURES DE NEGÓCIO (rotinas do legado)
-- =====================================================================

-- Geração de necessidade de follow-up (Qry_Necessidade_FollowUp_Fornecedor)
create or replace function fn_gerar_necessidade_followup() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  insert into followup_fornecedor
    (cd_compra, dt_revised_delivery_original, dt_recebimento_cb_original, dc_modal_original,
     dt_inicio_followup, dc_status_fornecedor, dc_avaliacao_comprador)
  select c.cd_compra, c.dt_revised_delivery, c.dt_recebimento, c.dc_modal,
         current_date, 'PENDENTE', 'PENDENTE'
  from controle_compras c
  left join vw_resumo_fup_comex x
    on c.cd_pedido_sap = x.cd_pedido_sap and c.cd_material_pai = x.cd_material_pai
  left join vw_followup_pendente p on c.cd_compra = p.cd_compra
  where c.dt_recebimento >= date_trunc('month', current_date)
    and coalesce(c.cd_pedido_fornecedor, '') not in ('', 'N/I')
    and x.dt_entrega_origem is null
    and p.cd_compra is null
    and c.dc_status is distinct from 'EXCLUIDO';
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Baixa automática de follow-ups (Qry_FollowFornecedor_BaixaAutomatica + update)
create or replace function fn_baixa_automatica_followup() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  with alvo as (
    select f.cd_follow_forn,
      case when x.cd_embarque is not null then 'Embarcado processo: ' || x.cd_embarque
           else 'Recebimento mês anterior' end as novo_status
    from followup_fornecedor f
    join controle_compras c on f.cd_compra = c.cd_compra
    left join vw_resumo_fup_comex x
      on c.cd_pedido_sap = x.cd_pedido_sap and c.cd_material_pai = x.cd_material_pai
    where f.dt_fim_followup is null
      and (
        c.dt_recebimento < date_trunc('month', current_date)
        or (x.cd_embarque is not null and x.dc_status_comex not ilike '%ORIGEM%')
      )
  )
  update followup_fornecedor f
  set dc_status_fornecedor = a.novo_status,
      dc_avaliacao_comprador = 'BAIXA AUTOMATICA',
      dc_observacao_avaliacao = a.novo_status,
      dt_fim_followup = current_date,
      dt_avaliacao_comprador = current_date
  from alvo a
  where f.cd_follow_forn = a.cd_follow_forn;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Sincroniza snapshot dos follows abertos com a compra (Qry_AtualizaInfos_FollowUp_Fornecedor)
create or replace function fn_atualiza_infos_followup() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  update followup_fornecedor f
  set dt_revised_delivery_original = c.dt_revised_delivery,
      dt_recebimento_cb_original = c.dt_recebimento,
      dc_modal_original = c.dc_modal
  from controle_compras c
  where f.cd_compra = c.cd_compra and f.dt_fim_followup is null;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Recalcular grupo de planejamento em massa (Qry_Recalcular_GrupoPlanejamento)
create or replace function fn_recalcular_grupo_planejamento() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  update controle_compras c
  set dc_grupo_planejamento = g.dc_grupo_planejamento
  from prm_grupo_planejamento g
  where c.dc_grupo = g.dc_grupo and c.dc_subgrupo = g.dc_subgrupo
    and c.dc_sexo = g.dc_sexo and c.dc_formato = g.dc_formato;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Ajuste manual de FOB (Qry_AjusteManual_Fob)
create or replace function fn_aplicar_ajuste_fob() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  update controle_compras c
  set nr_fob_negociado = a.nr_fob,
      nr_fob_real = a.nr_fob,
      nr_total_fob = c.nr_quantidade * a.nr_fob
  from prm_ajuste_fob a
  where c.cd_material_pai = a.cd_material_pai and c.cd_pedido_sap = a.cd_pedido_sap;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Atualização de cadastro PedidoSAP/MaterialPai (Qry_Atualizacao_AtualizacaoCadastro)
create or replace function fn_aplicar_ajuste_pedido_sap() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  update controle_compras c
  set cd_pedido_sap = a.cd_pedido_sap,
      cd_material_pai = a.cd_material_pai
  from prm_ajuste_pedido_sap_cadastro a
  where a.id_sysplan = c.cd_compra
    and a.cd_pedido_fornecedor = c.cd_pedido_fornecedor
    and a.cd_material_fornecedor = c.cd_material_fornecedor;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Alimenta de-para de múltiplos embarques (Qry_Alimenta_DePara_MultiplosEmbarques)
create or replace function fn_alimentar_depara_multiplos_embarques() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  insert into prm_depara_pedido_multiplos_embarques (cd_pedido_sap, cd_material_pai, cd_embarque)
  select distinct me.cd_pedido_sap, me.cd_material_pai, f.cd_embarque
  from vw_fup_multiplos_embarques me
  left join ext_fup_comex f
    on me.cd_pedido_sap = f.cd_pedido_sap and me.cd_material_pai = f.cd_material_pai
  left join prm_depara_pedido_multiplos_embarques d
    on f.cd_embarque = d.cd_embarque
   and f.cd_material_pai = d.cd_material_pai
   and f.cd_pedido_sap = d.cd_pedido_sap
  where d.codigo is null and f.cd_embarque is not null;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Atualiza EXT_Pedido_SAP a partir do snapshot BW (Qry_Atualizar_Pedido_SAP + Qry_Limpar_PedidoSAP)
create or replace function fn_atualizar_pedido_sap_bw() returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_qtd integer;
begin
  delete from ext_pedido_sap;
  insert into ext_pedido_sap
    (cd_pedido_sap, cd_material, cd_material_pai, nr_valor_fob, nr_quantidade, dc_modal, dc_cor_lente_solar, dc_cor_armacao)
  select b.oi_ebeln, b.material, left(b.material, 8),
         sum(b.net_po_val), sum(b.ttlqty), b.ca_modal,
         max(m.dc_cor_lente_solar), max(m.dc_cor_armacao)
  from ext_sap_pedido_bw b
  left join cadastro_material m on b.material = m.cd_material
  group by b.oi_ebeln, b.material, left(b.material, 8), b.ca_modal;
  get diagnostics v_qtd = row_count;
  return v_qtd;
end;
$$;

-- Bloqueio/desbloqueio de registro para edição (BloqueioRegistro do VBA)
create or replace function fn_bloquear_compra(p_cd_compra integer, p_bloquear boolean)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  v_lock_user uuid;
  v_lock boolean;
begin
  select bloqueio_edicao, usuario_bloqueio into v_lock, v_lock_user
  from controle_compras where cd_compra = p_cd_compra for update;

  if p_bloquear then
    -- lock expirado (>2h) é liberado automaticamente
    if v_lock and v_lock_user is not null and v_lock_user <> auth.uid()
       and exists (select 1 from controle_compras
                   where cd_compra = p_cd_compra and bloqueio_em > now() - interval '2 hours') then
      return false;
    end if;
    update controle_compras
    set bloqueio_edicao = true, usuario_bloqueio = auth.uid(), bloqueio_em = now()
    where cd_compra = p_cd_compra;
  else
    update controle_compras
    set bloqueio_edicao = false, usuario_bloqueio = null, bloqueio_em = null
    where cd_compra = p_cd_compra
      and (usuario_bloqueio = auth.uid() or fn_is_admin());
  end if;
  return true;
end;
$$;

-- ############ 00003_rls.sql ############

-- SysPlan Web — Row Level Security e políticas de acesso
-- Modelo: admins têm acesso total; usuários dependem de permissões por tela (tabela permissoes).
-- O service_role (migração/rotinas) tem BYPASSRLS nativo no Supabase.

-- Ajuste no trigger de auditoria: gravações de serviço (sem usuário autenticado,
-- ex.: migração de dados) não geram log automático.
create or replace function trg_audita_controle_compras() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_col text;
  v_old text;
  v_new text;
begin
  if auth.uid() is null then
    return new;
  end if;
  if tg_op = 'INSERT' then
    insert into log_transacoes (usuario_id, transacao, cd_item_transacao)
    values (auth.uid(), 'EdicaoCompra - Criacao', new.cd_compra);
    return new;
  end if;
  for v_col in
    select column_name from information_schema.columns
    where table_schema = 'public' and table_name = 'controle_compras'
      and column_name not in ('atualizado_em', 'criado_em', 'bloqueio_edicao', 'usuario_bloqueio', 'bloqueio_em', 'nr_margem', 'nr_anomes', 'nr_lead_time')
  loop
    execute format('select ($1).%I::text, ($2).%I::text', v_col, v_col) into v_old, v_new using old, new;
    if v_old is distinct from v_new then
      insert into log_transacoes (usuario_id, transacao, cd_item_transacao, info_anterior, info_atual, campo_editado)
      values (auth.uid(), 'EdicaoCompra - Alteracao', new.cd_compra, coalesce(v_old, ''), coalesce(v_new, ''), v_col);
    end if;
  end loop;
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- Habilita RLS em todas as tabelas
-- ---------------------------------------------------------------------
alter table usuarios enable row level security;
alter table telas enable row level security;
alter table permissoes enable row level security;
alter table log_transacoes enable row level security;
alter table prm_grupo enable row level security;
alter table prm_combos enable row level security;
alter table prm_grupo_planejamento enable row level security;
alter table prm_definicao_custo enable row level security;
alter table prm_cluster_comprador enable row level security;
alter table prm_ajuste_fob enable row level security;
alter table prm_ajuste_pedido_sap_cadastro enable row level security;
alter table prm_depara_pedido_multiplos_embarques enable row level security;
alter table prm_versao enable row level security;
alter table prm_campos_edicao_massa enable row level security;
alter table prm_cor_pi enable row level security;
alter table prm_depara_campos_pi enable row level security;
alter table prm_lista_compras enable row level security;
alter table usuario_lista_config enable row level security;
alter table cadastro_essential enable row level security;
alter table depara_essential enable row level security;
alter table cadastro_material enable row level security;
alter table cadastro_material_pai enable row level security;
alter table controle_compras enable row level security;
alter table followup_fornecedor enable row level security;
alter table ext_fup_comex enable row level security;
alter table ext_fup_despachante enable row level security;
alter table ext_pedido_sap enable row level security;
alter table ext_sap_pedido_bw enable row level security;
alter table stg_entrada_sap_mb51 enable row level security;
alter table pasta_pi enable row level security;
alter table pi_cores enable row level security;
alter table desenvolvimento_design enable row level security;
alter table cartela_cor_design enable row level security;
alter table pdv_cadastro_loja enable row level security;
alter table pdv_cadastro_pdv enable row level security;
alter table pdv_base_cadastro enable row level security;
alter table pdv_depara enable row level security;
alter table pdv_status enable row level security;
alter table importacoes enable row level security;

-- ---------------------------------------------------------------------
-- Usuários / permissões / telas
-- ---------------------------------------------------------------------
create policy usuarios_select on usuarios for select to authenticated using (true);
create policy usuarios_admin_all on usuarios for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

create policy telas_select on telas for select to authenticated using (true);
create policy telas_admin on telas for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

create policy permissoes_select_propria on permissoes for select to authenticated
  using (usuario_id = auth.uid() or fn_is_admin());
create policy permissoes_admin on permissoes for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

-- Logs: leitura restrita a admins; escrita via funções security definer
create policy log_admin_select on log_transacoes for select to authenticated
  using (fn_tem_permissao('admin_logs'));

-- ---------------------------------------------------------------------
-- Parâmetros: leitura para todos autenticados; escrita admin/parametros
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'prm_grupo', 'prm_combos', 'prm_grupo_planejamento', 'prm_definicao_custo',
    'prm_cluster_comprador', 'prm_ajuste_fob', 'prm_ajuste_pedido_sap_cadastro',
    'prm_versao', 'prm_campos_edicao_massa', 'prm_cor_pi',
    'prm_depara_campos_pi', 'prm_lista_compras',
    'cadastro_material', 'cadastro_material_pai', 'ext_sap_pedido_bw', 'ext_pedido_sap'
  ]
  loop
    execute format('create policy %I_sel on %I for select to authenticated using (true)', t, t);
    execute format(
      'create policy %I_adm on %I for all to authenticated using (fn_tem_permissao(''admin_parametros'', true)) with check (fn_tem_permissao(''admin_parametros'', true))',
      t, t);
  end loop;
end $$;

-- Configuração de lista por usuário: cada um gerencia a sua
create policy lista_config_own on usuario_lista_config for all to authenticated
  using (usuario_id = auth.uid()) with check (usuario_id = auth.uid());

-- ---------------------------------------------------------------------
-- Tabelas de negócio: leitura/escrita conforme permissão da tela
-- ---------------------------------------------------------------------
create policy compras_sel on controle_compras for select to authenticated
  using (fn_tem_permissao('lista_compras'));
create policy compras_ins on controle_compras for insert to authenticated
  with check (fn_tem_permissao('lista_compras', true));
create policy compras_upd on controle_compras for update to authenticated
  using (fn_tem_permissao('lista_compras', true));
-- Exclusão física não permitida (exclusão é lógica via DC_Status='EXCLUIDO')

create policy essential_sel on cadastro_essential for select to authenticated using (true);
create policy essential_adm on cadastro_essential for all to authenticated
  using (fn_tem_permissao('admin_parametros', true)) with check (fn_tem_permissao('admin_parametros', true));

create policy depara_essential_sel on depara_essential for select to authenticated using (true);
create policy depara_essential_edit on depara_essential for all to authenticated
  using (fn_tem_permissao('lista_compras', true)) with check (fn_tem_permissao('lista_compras', true));

create policy followup_sel on followup_fornecedor for select to authenticated
  using (fn_tem_permissao('followup_fornecedor'));
create policy followup_all on followup_fornecedor for all to authenticated
  using (fn_tem_permissao('followup_fornecedor', true)) with check (fn_tem_permissao('followup_fornecedor', true));

create policy fup_comex_sel on ext_fup_comex for select to authenticated
  using (fn_tem_permissao('controle_importacao') or fn_tem_permissao('lista_compras') or fn_tem_permissao('followup_fornecedor'));
create policy fup_comex_edit on ext_fup_comex for all to authenticated
  using (fn_tem_permissao('controle_importacao', true)) with check (fn_tem_permissao('controle_importacao', true));

create policy fup_desp_sel on ext_fup_despachante for select to authenticated
  using (fn_tem_permissao('controle_importacao') or fn_tem_permissao('lista_compras') or fn_tem_permissao('followup_fornecedor'));
create policy fup_desp_edit on ext_fup_despachante for all to authenticated
  using (fn_tem_permissao('controle_importacao', true)) with check (fn_tem_permissao('controle_importacao', true));

create policy mb51_sel on stg_entrada_sap_mb51 for select to authenticated
  using (fn_tem_permissao('checks_recebimento') or fn_tem_permissao('controle_importacao'));
create policy mb51_edit on stg_entrada_sap_mb51 for all to authenticated
  using (fn_tem_permissao('checks_recebimento', true)) with check (fn_tem_permissao('checks_recebimento', true));

create policy pasta_pi_sel on pasta_pi for select to authenticated
  using (fn_tem_permissao('cadastro_pi'));
create policy pasta_pi_all on pasta_pi for all to authenticated
  using (fn_tem_permissao('cadastro_pi', true)) with check (fn_tem_permissao('cadastro_pi', true));

create policy pi_cores_sel on pi_cores for select to authenticated
  using (fn_tem_permissao('cadastro_pi'));
create policy pi_cores_all on pi_cores for all to authenticated
  using (fn_tem_permissao('cadastro_pi', true)) with check (fn_tem_permissao('cadastro_pi', true));

create policy design_sel on desenvolvimento_design for select to authenticated
  using (fn_tem_permissao('design'));
create policy design_all on desenvolvimento_design for all to authenticated
  using (fn_tem_permissao('design', true)) with check (fn_tem_permissao('design', true));

create policy cartela_sel on cartela_cor_design for select to authenticated
  using (fn_tem_permissao('design'));
create policy cartela_all on cartela_cor_design for all to authenticated
  using (fn_tem_permissao('design', true)) with check (fn_tem_permissao('design', true));

do $$
declare
  t text;
begin
  foreach t in array array['pdv_cadastro_loja', 'pdv_cadastro_pdv', 'pdv_base_cadastro', 'pdv_depara', 'pdv_status']
  loop
    execute format('create policy %I_sel on %I for select to authenticated using (fn_tem_permissao(''cadastro_pdv''))', t, t);
    execute format(
      'create policy %I_all on %I for all to authenticated using (fn_tem_permissao(''cadastro_pdv'', true)) with check (fn_tem_permissao(''cadastro_pdv'', true))',
      t, t);
  end loop;
end $$;

create policy multiplos_sel on prm_depara_pedido_multiplos_embarques for select to authenticated
  using (fn_tem_permissao('multiplos_embarques') or fn_tem_permissao('controle_importacao') or fn_tem_permissao('lista_compras'));
create policy multiplos_all on prm_depara_pedido_multiplos_embarques for all to authenticated
  using (fn_tem_permissao('multiplos_embarques', true)) with check (fn_tem_permissao('multiplos_embarques', true));

create policy importacoes_own on importacoes for select to authenticated
  using (usuario_id = auth.uid() or fn_is_admin());
create policy importacoes_ins on importacoes for insert to authenticated
  with check (usuario_id = auth.uid());
create policy importacoes_upd on importacoes for update to authenticated
  using (usuario_id = auth.uid() or fn_is_admin());

-- ---------------------------------------------------------------------
-- Storage: buckets para fotos de produto e arquivos de PI
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('fotos-produto', 'fotos-produto', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('arquivos-pi', 'arquivos-pi', false)
on conflict (id) do nothing;

create policy storage_fotos_read on storage.objects for select to authenticated
  using (bucket_id = 'fotos-produto');
create policy storage_fotos_write on storage.objects for insert to authenticated
  with check (bucket_id = 'fotos-produto' and (fn_tem_permissao('cadastro_pi', true) or fn_tem_permissao('lista_compras', true)));
create policy storage_fotos_update on storage.objects for update to authenticated
  using (bucket_id = 'fotos-produto' and (fn_tem_permissao('cadastro_pi', true) or fn_tem_permissao('lista_compras', true)));
create policy storage_pi_read on storage.objects for select to authenticated
  using (bucket_id = 'arquivos-pi' and fn_tem_permissao('cadastro_pi'));
create policy storage_pi_write on storage.objects for insert to authenticated
  with check (bucket_id = 'arquivos-pi' and fn_tem_permissao('cadastro_pi', true));

-- ############ 00004_seed.sql ############

-- SysPlan Web — Seed: catálogo de telas e função de pós-migração

insert into telas (codigo, nome, grupo, ordem) values
  ('lista_compras',       'Lista de Compras',          'Compras',       1),
  ('followup_fornecedor', 'Follow-up Fornecedor',      'Compras',       2),
  ('cadastro_pi',         'Cadastro de PI',            'Compras',       3),
  ('controle_importacao', 'Controle de Importação',    'Comex',         4),
  ('multiplos_embarques', 'Múltiplos Embarques',       'Comex',         5),
  ('checks_recebimento',  'Checks de Recebimento',     'Comex',         6),
  ('cadastro_pdv',        'Cadastro de PDV',           'Cadastros',     7),
  ('design',              'Desenvolvimento Design',    'Cadastros',     8),
  ('admin_usuarios',      'Usuários',                  'Administração', 20),
  ('admin_permissoes',    'Permissões',                'Administração', 21),
  ('admin_parametros',    'Parâmetros',                'Administração', 22),
  ('admin_logs',          'Logs',                      'Administração', 23),
  ('admin_importacoes',   'Importações',               'Administração', 24)
on conflict (codigo) do nothing;

-- Após importar os dados legados com IDs explícitos, realinha as sequences.
-- Chamada via RPC pelo script de migração (service_role).
create or replace function fn_pos_migracao() returns text
language plpgsql security definer set search_path = public as $$
begin
  perform setval(pg_get_serial_sequence('controle_compras', 'cd_compra'),
                 coalesce((select max(cd_compra) from controle_compras), 0) + 1, false);
  perform setval(pg_get_serial_sequence('followup_fornecedor', 'cd_follow_forn'),
                 coalesce((select max(cd_follow_forn) from followup_fornecedor), 0) + 1, false);
  perform setval(pg_get_serial_sequence('log_transacoes', 'cd_transacao'),
                 coalesce((select max(cd_transacao) from log_transacoes), 0) + 1, false);
  perform setval(pg_get_serial_sequence('cadastro_essential', 'cd_essential'),
                 coalesce((select max(cd_essential) from cadastro_essential), 0) + 1, false);
  perform setval(pg_get_serial_sequence('prm_grupo', 'cd_grupo'),
                 coalesce((select max(cd_grupo) from prm_grupo), 0) + 1, false);
  perform setval(pg_get_serial_sequence('prm_combos', 'cd_combo'),
                 coalesce((select max(cd_combo) from prm_combos), 0) + 1, false);
  perform setval(pg_get_serial_sequence('prm_cluster_comprador', 'cd_cluster'),
                 coalesce((select max(cd_cluster) from prm_cluster_comprador), 0) + 1, false);
  perform setval(pg_get_serial_sequence('prm_depara_pedido_multiplos_embarques', 'codigo'),
                 coalesce((select max(codigo) from prm_depara_pedido_multiplos_embarques), 0) + 1, false);
  perform setval(pg_get_serial_sequence('desenvolvimento_design', 'cd_desenvolv'),
                 coalesce((select max(cd_desenvolv) from desenvolvimento_design), 0) + 1, false);
  perform setval(pg_get_serial_sequence('cartela_cor_design', 'cd_cor_design'),
                 coalesce((select max(cd_cor_design) from cartela_cor_design), 0) + 1, false);
  perform setval(pg_get_serial_sequence('pdv_cadastro_pdv', 'id_pdv'),
                 coalesce((select max(id_pdv) from pdv_cadastro_pdv), 0) + 1, false);
  return 'ok';
end;
$$;

-- Vincula usuários legados (DM_Usuarios) aos novos cadastros por e-mail,
-- preenchendo cd_usuario_legado/login_rede/filtro_comprador quando o usuário
-- do Auth for criado com o mesmo e-mail.
create table if not exists usuarios_legado (
  cd_usuario integer primary key,
  cd_login_rede text,
  dc_email text,
  dc_filtro_comprador text
);
alter table usuarios_legado enable row level security;
create policy usuarios_legado_admin on usuarios_legado for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

create or replace function trg_vincula_usuario_legado() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_leg usuarios_legado%rowtype;
begin
  select * into v_leg from usuarios_legado
  where lower(dc_email) = lower(new.email) limit 1;
  if found then
    new.cd_usuario_legado := v_leg.cd_usuario;
    new.login_rede := v_leg.cd_login_rede;
    new.filtro_comprador := coalesce(v_leg.dc_filtro_comprador, 'GERAL');
  end if;
  return new;
end;
$$;

create trigger vincula_usuario_legado
  before insert on usuarios
  for each row execute function trg_vincula_usuario_legado();
