-- SysPlan Web — Schema principal
-- Convertido do Access (SysPlan_BD.accdb + tabelas locais do frontend)

-- =====================================================================
-- USUÁRIOS, PERFIS E PERMISSÕES
-- =====================================================================

create type perfil_usuario as enum ('admin', 'usuario');

create table usuarios (
  id uuid primary key references auth.users (id) on delete cascade,
  cd_usuario_legado integer unique,
  nome text not null default '',
  email text not null unique,
  login_rede text,
  filtro_comprador text default 'GERAL',
  perfil perfil_usuario not null default 'usuario',
  bloqueado boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Catálogo de telas/módulos do sistema (permissões por tela)
create table telas (
  codigo text primary key,
  nome text not null,
  grupo text not null default 'Sistema',
  ordem integer not null default 0
);

create table permissoes (
  usuario_id uuid not null references usuarios (id) on delete cascade,
  tela_codigo text not null references telas (codigo) on delete cascade,
  pode_visualizar boolean not null default true,
  pode_editar boolean not null default false,
  primary key (usuario_id, tela_codigo)
);

-- Log de auditoria (legado: DM_RegistroTransacao_Usuario)
create table log_transacoes (
  cd_transacao bigint generated by default as identity primary key,
  usuario_id uuid references usuarios (id),
  cd_usuario_legado integer,
  transacao text not null,
  cd_item_transacao integer default 0,
  dt_transacao timestamptz not null default now(),
  info_anterior text,
  info_atual text,
  campo_editado text
);

create index idx_log_transacoes_item on log_transacoes (cd_item_transacao);
create index idx_log_transacoes_dt on log_transacoes (dt_transacao desc);
create index idx_log_transacoes_usuario on log_transacoes (usuario_id);
create index idx_log_transacoes_transacao on log_transacoes (transacao);

-- =====================================================================
-- PARÂMETROS (PRM)
-- =====================================================================

create table prm_grupo (
  cd_grupo integer generated by default as identity primary key,
  dc_grupo text not null unique
);

create table prm_combos (
  cd_combo integer generated by default as identity primary key,
  cd_grupo integer not null references prm_grupo (cd_grupo),
  dc_tipo_combo text not null,
  dc_combo text not null
);
create index idx_prm_combos_tipo on prm_combos (cd_grupo, dc_tipo_combo);

create table prm_grupo_planejamento (
  dc_grupo text not null,
  dc_subgrupo text not null,
  dc_sexo text not null,
  dc_formato text not null,
  dc_grupo_planejamento text,
  primary key (dc_grupo, dc_subgrupo, dc_sexo, dc_formato)
);

create table prm_definicao_custo (
  dc_canal text not null,
  dc_grupo text not null,
  dc_modal text not null,
  nr_anomes numeric not null,
  nr_dolar double precision default 0,
  nr_fator_imp double precision default 0,
  nr_markup double precision default 0,
  nr_valor_agregado double precision default 0,
  primary key (dc_canal, dc_grupo, dc_modal, nr_anomes)
);

create table prm_cluster_comprador (
  cd_cluster integer generated by default as identity primary key,
  dc_grupo text,
  dc_canal text,
  dc_comprador text,
  dc_comprador_grupo text
);

create table prm_ajuste_fob (
  cd_pedido_sap text not null,
  cd_material_pai text not null,
  nr_fob double precision default 0,
  primary key (cd_pedido_sap, cd_material_pai)
);

create table prm_ajuste_pedido_sap_cadastro (
  id_sysplan integer primary key,
  cd_pedido_fornecedor text,
  cd_material_fornecedor text,
  cd_pedido_sap text,
  cd_material_pai text
);

create table prm_depara_pedido_multiplos_embarques (
  codigo integer generated by default as identity primary key,
  cd_pedido_sap text,
  cd_material_pai text,
  cd_embarque text,
  cd_pedido_sap_ajuste text
);
create index idx_prm_multiplos_chave on prm_depara_pedido_multiplos_embarques (cd_pedido_sap, cd_material_pai, cd_embarque);

create table prm_versao (
  versao_atual text primary key
);

-- Mapa de campos da edição em massa (legado: PRM_Campos_EdicaoMassa_Compras)
create table prm_campos_edicao_massa (
  dc_campo_edicao text primary key,
  dc_campo_original text,
  dc_campo_sysplan text
);

-- Dicionário de tradução de cores da PI (legado: PRM_Cor_PI)
create table prm_cor_pi (
  id integer generated always as identity primary key,
  dc_campo text,
  dc_texto_portugues text,
  dc_texto_ingles text,
  cd_codigo_cor text,
  ordem_pesquisa integer default 0
);

-- De-para de valores da PI para combos (legado: PRM_DePara_CamposPI)
create table prm_depara_campos_pi (
  id integer generated always as identity primary key,
  cd_grupo integer,
  dc_tipo_combo text,
  info_de text,
  info_para text
);

-- Configuração padrão de colunas da lista de compras (legado: PRM_Lista_Compras)
create table prm_lista_compras (
  campo text primary key,
  exibir text default 'SIM',
  tipo_filtro text default '',
  filtro text default '',
  largura_coluna integer default 100,
  legenda_exibicao text,
  ordem integer default 0,
  formatacao text,
  order_by text default 'NAO',
  tipo_dado text default 'Texto',
  largura_coluna_original integer default 100
);

-- Configuração de lista por usuário (novo: substitui config global do Access)
create table usuario_lista_config (
  usuario_id uuid not null references usuarios (id) on delete cascade,
  campo text not null references prm_lista_compras (campo) on delete cascade,
  exibir text default 'SIM',
  tipo_filtro text default '',
  filtro text default '',
  largura_coluna integer default 100,
  ordem integer default 0,
  order_by text default 'NAO',
  primary key (usuario_id, campo)
);

-- =====================================================================
-- CADASTROS DE APOIO
-- =====================================================================

create table cadastro_essential (
  cd_essential integer generated by default as identity primary key,
  dc_grupo text,
  dc_essential text,
  cd_material_pai_atual text,
  cd_ref_exportador_atual text,
  dc_status text,
  dc_reposicao_automatica text,
  vermelha boolean not null default false,
  otica boolean not null default false,
  dc_cluster_loja text,
  dc_status_vermelha text,
  dc_status_otica text
);

create table depara_essential (
  cd_material_pai text not null,
  cd_ref_exportador text not null,
  cd_essential text not null,
  primary key (cd_material_pai, cd_ref_exportador, cd_essential)
);

-- Snapshot do cadastro de materiais (legado: DB_Cadastro.accdb, linked)
create table cadastro_material (
  cd_material text primary key,
  cd_material_pai text,
  grupo2 text,
  dc_cor_lente_solar text,
  dc_cor_armacao text,
  dados jsonb
);
create index idx_cadastro_material_pai on cadastro_material (cd_material_pai);

create table cadastro_material_pai (
  cd_material_pai text primary key,
  dc_grupo text,
  grupo2 text,
  dados jsonb
);

-- =====================================================================
-- CONTROLE DE COMPRAS (tabela central)
-- =====================================================================

create table controle_compras (
  cd_compra integer generated by default as identity primary key,
  dc_status text,
  dc_canal text,
  dc_grupo text,
  dc_subgrupo text,
  dc_formato text,
  dc_sexo text,
  dc_segmentacao text,
  dc_grupo_planejamento text,
  dc_linha text,
  dc_griffe text,
  dc_material1 text,
  dc_material2 text,
  dc_atributo1 text,
  dc_atributo2 text,
  dc_medidas text,
  dc_tamanho text,
  dc_info1 text,
  dc_info2 text,
  dc_info3 text,
  dc_info4 text,
  dc_info5 text,
  dc_info6 text,
  dc_info7 text,
  nr_fob_negociado double precision default 0,
  nr_fob_real double precision default 0,
  nr_quantidade double precision default 0,
  nr_preco_varejo double precision default 0,
  nr_margem double precision default 0,
  cd_material_fornecedor text,
  cd_material_pai text,
  dc_fornecedor text,
  cd_pedido_fornecedor text,
  cd_pedido_sap text,
  dc_modal text,
  dt_recebimento date,
  dt_delivery date,
  dt_revised_delivery date,
  nr_lead_time double precision,
  dc_observacao text,
  nr_anomes numeric,
  bloqueio_edicao boolean not null default false,
  usuario_bloqueio uuid references usuarios (id),
  bloqueio_em timestamptz,
  dc_fup_produto text,
  cd_essential integer default 0,
  dc_aprovacao_cor text,
  nr_total_fob double precision default 0,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_compras_status on controle_compras (dc_status);
create index idx_compras_pedido_sap on controle_compras (cd_pedido_sap, cd_material_pai);
create index idx_compras_pedido_forn on controle_compras (cd_pedido_fornecedor, cd_material_fornecedor);
create index idx_compras_anomes on controle_compras (nr_anomes);
create index idx_compras_recebimento on controle_compras (dt_recebimento);
create index idx_compras_grupo_canal on controle_compras (dc_grupo, dc_canal);

-- =====================================================================
-- FOLLOW-UP DE FORNECEDOR
-- =====================================================================

create table followup_fornecedor (
  cd_follow_forn integer generated by default as identity primary key,
  -- sem FK estrita: dados legados possuem cd_compra=0/órfãos (Access não tinha FK)
  cd_compra integer not null default 0,
  dt_revised_delivery_original date,
  dt_recebimento_cb_original date,
  dc_modal_original text,
  dc_status_fornecedor text,
  dc_observacao_fornecedor text,
  dt_revised_delivery_proposta date,
  dc_numero_bl text,
  dc_avaliacao_fornecedor text,
  dc_avaliacao_comprador text,
  dc_observacao_avaliacao text,
  dt_novo_recebimento_comprador date,
  dt_novo_delivery_comprador date,
  dc_novo_modal_comprador text,
  dc_avaliacao_final text,
  dt_inicio_followup date,
  dt_fim_followup date,
  dt_avaliacao_comprador date
);

create index idx_followup_compra on followup_fornecedor (cd_compra);
create index idx_followup_fim on followup_fornecedor (dt_fim_followup);

-- =====================================================================
-- BASES EXTERNAS (snapshots atualizáveis por importação)
-- =====================================================================

create table ext_fup_comex (
  id bigint generated always as identity primary key,
  cd_sequencia_embarque text,
  cd_embarque text,
  cd_pedido_sap text,
  cd_material text,
  cd_material_pai text,
  dt_entrega_origem date,
  dt_previsao_embarque date,
  dt_embarque_real date,
  dt_previsao_atraque date,
  dt_atraque_real date,
  dt_chegada_cb date,
  nr_quantidade double precision,
  nr_fob_total double precision,
  dc_status_comex text
);
create index idx_fup_comex_chave on ext_fup_comex (cd_pedido_sap, cd_material_pai);
create index idx_fup_comex_embarque on ext_fup_comex (cd_embarque);

create table ext_fup_despachante (
  id bigint generated always as identity primary key,
  cd_pedido_sap text,
  cd_material_pai text,
  cd_embarque text,
  dt_entrega_origem date,
  dt_previsao_embarque date,
  dt_embarque_real date,
  dt_previsao_atraque date,
  dt_atraque_real date,
  hbl text,
  dc_status_comex text,
  dc_observacao text,
  origem text
);
create index idx_fup_desp_chave on ext_fup_despachante (cd_pedido_sap, cd_material_pai);

create table ext_pedido_sap (
  id bigint generated always as identity primary key,
  cd_pedido_sap text,
  cd_material text,
  cd_material_pai text,
  nr_valor_fob numeric,
  nr_quantidade numeric,
  dc_modal text,
  dc_cor_lente_solar text,
  dc_cor_armacao text
);
create index idx_pedido_sap_chave on ext_pedido_sap (cd_pedido_sap, cd_material_pai);

-- Snapshot do extrator SAP BW (legado: dbo./BIC/OHZSETTB023)
create table ext_sap_pedido_bw (
  comp_code text not null,
  oi_ebeln text not null,
  oi_ebelp text not null,
  recordmode text,
  material text,
  txt_material text,
  erdat text,
  vendor text,
  ca_impna text,
  dsdel_date text,
  doctype text,
  net_po_val numeric,
  ttlqty numeric,
  base_uom text,
  ca_modal text,
  txtlg text,
  order_curr text,
  primary key (comp_code, oi_ebeln, oi_ebelp)
);
create index idx_sap_bw_material on ext_sap_pedido_bw (material);

-- Entradas SAP MB51 (staging de conferência de recebimento)
create table stg_entrada_sap_mb51 (
  id bigint generated always as identity primary key,
  material text,
  centro text,
  deposito text,
  tipo_movimento text,
  txt_tipo_movimento text,
  doc_material text,
  item_doc_material text,
  dt_lancamento date,
  qtd_um_registro double precision,
  um_registro text,
  montante_mi double precision,
  referencia text,
  cliente text,
  fornecedor text,
  nome1 text,
  nome_usuario text,
  pedido text,
  texto_breve_material text,
  importado_em timestamptz not null default now()
);
create index idx_mb51_chave on stg_entrada_sap_mb51 (pedido, material);

-- =====================================================================
-- CADASTRO DE PI (Proforma Invoice)
-- =====================================================================

create table pasta_pi (
  dc_nome_arquivo text primary key,
  dc_caminho_arquivo text,
  dc_tipo_arquivo text,
  dt_modificacao_arquivo timestamptz,
  dc_status_movimentacao text,
  cd_sysplan integer default 0,
  dc_sore text,
  cd_pi text,
  dt_delivery_date date,
  cd_ref_fornecedor text,
  dc_fornecedor text,
  dc_reorder text,
  cd_last_model text,
  dc_griffe text,
  nr_qtd_total double precision default 0,
  nr_fob_total double precision default 0,
  dc_frame1 text,
  dc_frame2 text,
  dc_lens text,
  dc_atributo1 text,
  dc_atributo2 text,
  dc_atributo3 text,
  dc_flap text,
  dc_hinge text,
  dc_size text,
  dc_temple1 text,
  dc_temple2 text,
  dc_bridge text,
  dc_rim text,
  dc_tips text,
  dc_nose_pad text,
  dc_lens_category text,
  dc_lens_tratamento1 text,
  dc_lens_tratamento2 text,
  dc_clipon_type text,
  dc_possui_foto text,
  storage_path_arquivo text,
  storage_path_foto text,
  importado_por uuid references usuarios (id),
  importado_em timestamptz default now()
);

-- Cores extraídas da PI (por importação; legado: AUX_Import_PI_Cores)
create table pi_cores (
  id bigint generated always as identity primary key,
  dc_nome_arquivo text not null references pasta_pi (dc_nome_arquivo) on delete cascade,
  dc_numero_cor text,
  dc_cor_lente text,
  dc_cor_armacao text,
  dc_acabamento_armacao text,
  dc_cor_haste text,
  dc_acabamento_haste text,
  nr_qtde double precision default 0,
  nr_fob double precision default 0,
  dc_idioma text not null default 'PORTUGUES',
  nr_total_fob double precision
);

-- =====================================================================
-- MÓDULO DESIGN (estrutura preservada do legado, sem dados)
-- =====================================================================

create table desenvolvimento_design (
  cd_desenvolv integer generated by default as identity primary key,
  cd_compra integer default 0,
  dc_fornecedor text,
  cd_codigo1 text,
  cd_codigo2 text,
  dt_escolha_modelagem date,
  dt_desenv_aprov_caito date,
  dt_desenvolv_envio_fornecedor date,
  dt_desenvolv_envio_licenciamento date,
  dt_desenho_tecnico_aprovacao date,
  dt_prototipo_aprovacao date,
  dt_prototipo_aprovacao_caito date,
  dt_lente_acetato_aprovacao date,
  dc_desenvolv_obs text,
  dc_desenvolv_status text
);

create table cartela_cor_design (
  cd_cor_design integer generated by default as identity primary key,
  cd_desenvolv integer references desenvolvimento_design (cd_desenvolv) on delete cascade,
  dc_cor_status text,
  dt_cor_aprovacao date,
  dt_cor_aprovacao_licenciamento date,
  dt_cor_aprovacao_caito date,
  dt_rec_foto_amostra date,
  dt_rec_amostra_fisica date,
  dt_rec_foto_amostra_final date,
  dt_rec_amostra_fisica_final date,
  dt_foto_final_envio_licenciamento date
);

-- =====================================================================
-- MÓDULO PDV (snapshot das tabelas CIG do SQL Server)
-- =====================================================================

create table pdv_cadastro_loja (
  cd_sap text primary key,
  dc_loja text,
  dc_canal text,
  dc_grupo_loja text,
  dc_franqueado text,
  dc_uf text,
  dc_estado text,
  dc_cidade text,
  dc_bairro text,
  dados jsonb
);

create table pdv_cadastro_pdv (
  id_pdv integer generated by default as identity primary key,
  cd_pdv text,
  dc_pdv text,
  dc_canal text,
  dc_tipo_pdv text,
  dc_franqueado text,
  dc_uf text,
  dc_estado text,
  dc_cidade text,
  dc_bairro text,
  dados jsonb
);

create table pdv_base_cadastro (
  cd_sap text primary key,
  dt_inicio_var date,
  dt_fim_var date,
  dt_inicio_atac date,
  dt_fim_atac date,
  dt_inicio_dev date,
  dt_fim_dev date,
  ultimo_movimento date,
  dados jsonb
);

create table pdv_depara (
  id_pdv integer not null,
  cd_sap text not null primary key
);

create table pdv_status (
  id bigint generated always as identity primary key,
  dados jsonb
);

-- =====================================================================
-- IMPORTAÇÕES / EXPORTAÇÕES (controle de jobs)
-- =====================================================================

create table importacoes (
  id bigint generated always as identity primary key,
  usuario_id uuid references usuarios (id),
  tipo text not null,           -- edicao_massa | followup_fornecedor | fup_despachante | mb51 | pi | pedido_sap_bw | ...
  nome_arquivo text,
  total_linhas integer default 0,
  linhas_validas integer default 0,
  linhas_erro integer default 0,
  status text not null default 'validando',  -- validando | aguardando_confirmacao | aplicado | cancelado | erro
  inconsistencias jsonb,
  criado_em timestamptz not null default now(),
  aplicado_em timestamptz
);
